// Generated by services/API/scripts/generate-api-contract.mjs. Do not edit directly.
import Foundation

public enum APIAccess: String, Sendable {
    case publicAccess = "public"
    case authenticated
}

public enum HTTPMethod: String, Sendable {
    case get = "GET"
    case post = "POST"
    case put = "PUT"
    case delete = "DELETE"
    case patch = "PATCH"
}

public enum APIRouteID: String, CaseIterable, Sendable {
    case publicInvite
    case publicCatalog
    case githubWebhook
    case stripeWebhook
    case googleOAuthCallback
    case githubOAuthCallback
    case xOAuthCallback
    case providerOAuthCallback
    case quickBooksOAuthCallback
    case plaidCallback
    case bootstrap
    case billingSummary
    case billingCheckout
    case billingPortal
    case botTemplateInstall
    case botCreate
    case botUpdate
    case botDelete
    case botInboxList
    case botInboxEnable
    case botInboxUpdate
    case botInboxDisable
    case botInboxRotate
    case botInboxMessageDelete
    case botMemoryList
    case botMemoryCreate
    case botMemoryUpdate
    case botMemoryDelete
    case botWorkspaceList
    case botWorkspaceAdd
    case botWorkspaceExport
    case botWorkspaceDownload
    case botWorkspaceDelete
    case botDocuments
    case botMessagesList
    case botMessageSend
    case botDesktopActionRecord
    case botMessagesClear
    case botMessageApprove
    case botMessageCancel
    case browserStatus
    case browserOpen
    case browserResume
    case browserClose
    case browserProfileDelete
    case botSchedulesList
    case botScheduleCreate
    case botScheduleUpdate
    case botScheduleDelete
    case botScheduleRun
    case botScheduleRuns
    case groupCreate
    case groupUpdate
    case groupDelete
    case groupDecisionCreate
    case groupDecisionDelete
    case groupMemoryList
    case groupMemoryCreate
    case groupMemoryUpdate
    case groupMemoryDelete
    case groupWorkspaceList
    case groupWorkspaceAdd
    case groupWorkspaceExport
    case groupWorkspaceDownload
    case groupWorkspaceDelete
    case groupInviteCreate
    case groupInviteJoin
    case groupMemberDelete
    case groupMessagesList
    case groupMessageSend
    case groupFileDownload
    case groupSchedulesList
    case groupScheduleCreate
    case groupScheduleUpdate
    case groupScheduleDelete
    case groupScheduleRun
    case groupScheduleRuns
    case groupRunCancel
    case groupTaskApproval
    case groupRoutinesList
    case groupRoutineRuns
    case groupRoutineCreate
    case groupRoutineUpdate
    case groupRoutineDelete
    case groupRoutinePreview
    case pushTokenPut
    case pushTokenDelete
    case uploadCreate
    case uploadComplete
    case fileDownload
    case memoryList
    case memoryCreate
    case memoryExport
    case memoryUpdate
    case memoryDelete
    case sharesList
    case shareCreate
    case shareDelete
    case shareImport
    case skillCreate
    case githubSkillsScan
    case githubSkillPreview
    case skillGet
    case skillUpdate
    case skillShare
    case skillShareImport
    case connectionsList
    case homeAssistantConnect
    case mcpServerConnect
    case mcpServerRename
    case connectionAuthorize
    case connectionDelete
    case accountDelete
}

public enum APIContractError: Error, Equatable, Sendable {
    case unknownRoute(APIRouteID)
    case missingPathParameter(String)
    case invalidPathParameter(String)
}

public struct APIContractRoute: Sendable {
    public let id: APIRouteID
    public let method: HTTPMethod
    public let pathTemplate: String
    public let access: APIAccess

    public func path(
        parameters: [String: String] = [:],
        queryItems: [URLQueryItem] = []
    ) throws -> String {
        var result = pathTemplate
        let expression = try NSRegularExpression(pattern: #"\{([^}]+)\}"#)
        let matches = expression.matches(
            in: result,
            range: NSRange(result.startIndex..., in: result)
        ).reversed()
        var pathAllowed = CharacterSet.urlPathAllowed
        pathAllowed.remove(charactersIn: "/?#")
        for match in matches {
            guard let nameRange = Range(match.range(at: 1), in: result) else { continue }
            let name = String(result[nameRange])
            guard let value = parameters[name] else {
                throw APIContractError.missingPathParameter(name)
            }
            guard let encoded = value.addingPercentEncoding(withAllowedCharacters: pathAllowed),
                  let matchRange = Range(match.range(at: 0), in: result)
            else { throw APIContractError.invalidPathParameter(name) }
            result.replaceSubrange(matchRange, with: encoded)
        }
        guard !queryItems.isEmpty else { return result }
        var components = URLComponents()
        components.percentEncodedPath = result
        components.queryItems = queryItems
        guard let encoded = components.url?.absoluteString else { return result }
        return encoded
    }
}

public enum GeneratedAPIContract {
    public static let routes: [APIRouteID: APIContractRoute] = [
        .publicInvite: APIContractRoute(
            id: .publicInvite,
            method: .get,
            pathTemplate: "/public/invites/{kind}/{token}",
            access: .publicAccess
        ),
        .publicCatalog: APIContractRoute(
            id: .publicCatalog,
            method: .get,
            pathTemplate: "/public/catalog",
            access: .publicAccess
        ),
        .githubWebhook: APIContractRoute(
            id: .githubWebhook,
            method: .post,
            pathTemplate: "/public/webhooks/github",
            access: .publicAccess
        ),
        .stripeWebhook: APIContractRoute(
            id: .stripeWebhook,
            method: .post,
            pathTemplate: "/public/webhooks/stripe",
            access: .publicAccess
        ),
        .googleOAuthCallback: APIContractRoute(
            id: .googleOAuthCallback,
            method: .get,
            pathTemplate: "/public/oauth/google/callback",
            access: .publicAccess
        ),
        .githubOAuthCallback: APIContractRoute(
            id: .githubOAuthCallback,
            method: .get,
            pathTemplate: "/public/oauth/github/callback",
            access: .publicAccess
        ),
        .xOAuthCallback: APIContractRoute(
            id: .xOAuthCallback,
            method: .get,
            pathTemplate: "/public/oauth/x/callback",
            access: .publicAccess
        ),
        .providerOAuthCallback: APIContractRoute(
            id: .providerOAuthCallback,
            method: .get,
            pathTemplate: "/public/oauth/provider/callback",
            access: .publicAccess
        ),
        .quickBooksOAuthCallback: APIContractRoute(
            id: .quickBooksOAuthCallback,
            method: .get,
            pathTemplate: "/public/oauth/quickbooks/callback",
            access: .publicAccess
        ),
        .plaidCallback: APIContractRoute(
            id: .plaidCallback,
            method: .get,
            pathTemplate: "/public/plaid/callback",
            access: .publicAccess
        ),
        .bootstrap: APIContractRoute(
            id: .bootstrap,
            method: .get,
            pathTemplate: "/bootstrap",
            access: .authenticated
        ),
        .billingSummary: APIContractRoute(
            id: .billingSummary,
            method: .get,
            pathTemplate: "/billing",
            access: .authenticated
        ),
        .billingCheckout: APIContractRoute(
            id: .billingCheckout,
            method: .post,
            pathTemplate: "/billing/checkout",
            access: .authenticated
        ),
        .billingPortal: APIContractRoute(
            id: .billingPortal,
            method: .post,
            pathTemplate: "/billing/portal",
            access: .authenticated
        ),
        .botTemplateInstall: APIContractRoute(
            id: .botTemplateInstall,
            method: .post,
            pathTemplate: "/bot-templates/{templateId}/install",
            access: .authenticated
        ),
        .botCreate: APIContractRoute(
            id: .botCreate,
            method: .post,
            pathTemplate: "/bots",
            access: .authenticated
        ),
        .botUpdate: APIContractRoute(
            id: .botUpdate,
            method: .put,
            pathTemplate: "/bots/{botId}",
            access: .authenticated
        ),
        .botDelete: APIContractRoute(
            id: .botDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}",
            access: .authenticated
        ),
        .botInboxList: APIContractRoute(
            id: .botInboxList,
            method: .get,
            pathTemplate: "/bots/{botId}/inbox",
            access: .authenticated
        ),
        .botInboxEnable: APIContractRoute(
            id: .botInboxEnable,
            method: .post,
            pathTemplate: "/bots/{botId}/inbox",
            access: .authenticated
        ),
        .botInboxUpdate: APIContractRoute(
            id: .botInboxUpdate,
            method: .put,
            pathTemplate: "/bots/{botId}/inbox",
            access: .authenticated
        ),
        .botInboxDisable: APIContractRoute(
            id: .botInboxDisable,
            method: .delete,
            pathTemplate: "/bots/{botId}/inbox",
            access: .authenticated
        ),
        .botInboxRotate: APIContractRoute(
            id: .botInboxRotate,
            method: .post,
            pathTemplate: "/bots/{botId}/inbox/rotate",
            access: .authenticated
        ),
        .botInboxMessageDelete: APIContractRoute(
            id: .botInboxMessageDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}/inbox/{messageId}",
            access: .authenticated
        ),
        .botMemoryList: APIContractRoute(
            id: .botMemoryList,
            method: .get,
            pathTemplate: "/bots/{botId}/memory",
            access: .authenticated
        ),
        .botMemoryCreate: APIContractRoute(
            id: .botMemoryCreate,
            method: .post,
            pathTemplate: "/bots/{botId}/memory",
            access: .authenticated
        ),
        .botMemoryUpdate: APIContractRoute(
            id: .botMemoryUpdate,
            method: .put,
            pathTemplate: "/bots/{botId}/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .botMemoryDelete: APIContractRoute(
            id: .botMemoryDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .botWorkspaceList: APIContractRoute(
            id: .botWorkspaceList,
            method: .get,
            pathTemplate: "/bots/{botId}/workspace/files",
            access: .authenticated
        ),
        .botWorkspaceAdd: APIContractRoute(
            id: .botWorkspaceAdd,
            method: .post,
            pathTemplate: "/bots/{botId}/workspace/files",
            access: .authenticated
        ),
        .botWorkspaceExport: APIContractRoute(
            id: .botWorkspaceExport,
            method: .get,
            pathTemplate: "/bots/{botId}/workspace/export",
            access: .authenticated
        ),
        .botWorkspaceDownload: APIContractRoute(
            id: .botWorkspaceDownload,
            method: .get,
            pathTemplate: "/bots/{botId}/workspace/files/{workspaceFileId}/download",
            access: .authenticated
        ),
        .botWorkspaceDelete: APIContractRoute(
            id: .botWorkspaceDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}/workspace/files/{workspaceFileId}",
            access: .authenticated
        ),
        .botDocuments: APIContractRoute(
            id: .botDocuments,
            method: .get,
            pathTemplate: "/bots/{botId}/documents",
            access: .authenticated
        ),
        .botMessagesList: APIContractRoute(
            id: .botMessagesList,
            method: .get,
            pathTemplate: "/bots/{botId}/messages",
            access: .authenticated
        ),
        .botMessageSend: APIContractRoute(
            id: .botMessageSend,
            method: .post,
            pathTemplate: "/bots/{botId}/messages",
            access: .authenticated
        ),
        .botDesktopActionRecord: APIContractRoute(
            id: .botDesktopActionRecord,
            method: .post,
            pathTemplate: "/bots/{botId}/desktop-actions",
            access: .authenticated
        ),
        .botMessagesClear: APIContractRoute(
            id: .botMessagesClear,
            method: .delete,
            pathTemplate: "/bots/{botId}/messages",
            access: .authenticated
        ),
        .botMessageApprove: APIContractRoute(
            id: .botMessageApprove,
            method: .post,
            pathTemplate: "/bots/{botId}/messages/{turnId}/approve",
            access: .authenticated
        ),
        .botMessageCancel: APIContractRoute(
            id: .botMessageCancel,
            method: .post,
            pathTemplate: "/bots/{botId}/messages/{turnId}/cancel",
            access: .authenticated
        ),
        .browserStatus: APIContractRoute(
            id: .browserStatus,
            method: .get,
            pathTemplate: "/bots/{botId}/browser",
            access: .authenticated
        ),
        .browserOpen: APIContractRoute(
            id: .browserOpen,
            method: .post,
            pathTemplate: "/bots/{botId}/browser/open",
            access: .authenticated
        ),
        .browserResume: APIContractRoute(
            id: .browserResume,
            method: .post,
            pathTemplate: "/bots/{botId}/browser/resume",
            access: .authenticated
        ),
        .browserClose: APIContractRoute(
            id: .browserClose,
            method: .post,
            pathTemplate: "/bots/{botId}/browser/close",
            access: .authenticated
        ),
        .browserProfileDelete: APIContractRoute(
            id: .browserProfileDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}/browser/profile",
            access: .authenticated
        ),
        .botSchedulesList: APIContractRoute(
            id: .botSchedulesList,
            method: .get,
            pathTemplate: "/bots/{botId}/schedules",
            access: .authenticated
        ),
        .botScheduleCreate: APIContractRoute(
            id: .botScheduleCreate,
            method: .post,
            pathTemplate: "/bots/{botId}/schedules",
            access: .authenticated
        ),
        .botScheduleUpdate: APIContractRoute(
            id: .botScheduleUpdate,
            method: .put,
            pathTemplate: "/bots/{botId}/schedules/{scheduleId}",
            access: .authenticated
        ),
        .botScheduleDelete: APIContractRoute(
            id: .botScheduleDelete,
            method: .delete,
            pathTemplate: "/bots/{botId}/schedules/{scheduleId}",
            access: .authenticated
        ),
        .botScheduleRun: APIContractRoute(
            id: .botScheduleRun,
            method: .post,
            pathTemplate: "/bots/{botId}/schedules/{scheduleId}/run",
            access: .authenticated
        ),
        .botScheduleRuns: APIContractRoute(
            id: .botScheduleRuns,
            method: .get,
            pathTemplate: "/bots/{botId}/runs",
            access: .authenticated
        ),
        .groupCreate: APIContractRoute(
            id: .groupCreate,
            method: .post,
            pathTemplate: "/groups",
            access: .authenticated
        ),
        .groupUpdate: APIContractRoute(
            id: .groupUpdate,
            method: .put,
            pathTemplate: "/groups/{groupId}",
            access: .authenticated
        ),
        .groupDelete: APIContractRoute(
            id: .groupDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}",
            access: .authenticated
        ),
        .groupDecisionCreate: APIContractRoute(
            id: .groupDecisionCreate,
            method: .post,
            pathTemplate: "/groups/{groupId}/decisions",
            access: .authenticated
        ),
        .groupDecisionDelete: APIContractRoute(
            id: .groupDecisionDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/decisions/{decisionId}",
            access: .authenticated
        ),
        .groupMemoryList: APIContractRoute(
            id: .groupMemoryList,
            method: .get,
            pathTemplate: "/groups/{groupId}/memory",
            access: .authenticated
        ),
        .groupMemoryCreate: APIContractRoute(
            id: .groupMemoryCreate,
            method: .post,
            pathTemplate: "/groups/{groupId}/memory",
            access: .authenticated
        ),
        .groupMemoryUpdate: APIContractRoute(
            id: .groupMemoryUpdate,
            method: .put,
            pathTemplate: "/groups/{groupId}/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .groupMemoryDelete: APIContractRoute(
            id: .groupMemoryDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .groupWorkspaceList: APIContractRoute(
            id: .groupWorkspaceList,
            method: .get,
            pathTemplate: "/groups/{groupId}/workspace/files",
            access: .authenticated
        ),
        .groupWorkspaceAdd: APIContractRoute(
            id: .groupWorkspaceAdd,
            method: .post,
            pathTemplate: "/groups/{groupId}/workspace/files",
            access: .authenticated
        ),
        .groupWorkspaceExport: APIContractRoute(
            id: .groupWorkspaceExport,
            method: .get,
            pathTemplate: "/groups/{groupId}/workspace/export",
            access: .authenticated
        ),
        .groupWorkspaceDownload: APIContractRoute(
            id: .groupWorkspaceDownload,
            method: .get,
            pathTemplate: "/groups/{groupId}/workspace/files/{workspaceFileId}/download",
            access: .authenticated
        ),
        .groupWorkspaceDelete: APIContractRoute(
            id: .groupWorkspaceDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/workspace/files/{workspaceFileId}",
            access: .authenticated
        ),
        .groupInviteCreate: APIContractRoute(
            id: .groupInviteCreate,
            method: .post,
            pathTemplate: "/groups/{groupId}/invites",
            access: .authenticated
        ),
        .groupInviteJoin: APIContractRoute(
            id: .groupInviteJoin,
            method: .post,
            pathTemplate: "/group-invites/{token}/join",
            access: .authenticated
        ),
        .groupMemberDelete: APIContractRoute(
            id: .groupMemberDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/members/{memberId}",
            access: .authenticated
        ),
        .groupMessagesList: APIContractRoute(
            id: .groupMessagesList,
            method: .get,
            pathTemplate: "/groups/{groupId}/messages",
            access: .authenticated
        ),
        .groupMessageSend: APIContractRoute(
            id: .groupMessageSend,
            method: .post,
            pathTemplate: "/groups/{groupId}/messages",
            access: .authenticated
        ),
        .groupFileDownload: APIContractRoute(
            id: .groupFileDownload,
            method: .get,
            pathTemplate: "/groups/{groupId}/files/{fileId}/download",
            access: .authenticated
        ),
        .groupSchedulesList: APIContractRoute(
            id: .groupSchedulesList,
            method: .get,
            pathTemplate: "/groups/{groupId}/schedules",
            access: .authenticated
        ),
        .groupScheduleCreate: APIContractRoute(
            id: .groupScheduleCreate,
            method: .post,
            pathTemplate: "/groups/{groupId}/schedules",
            access: .authenticated
        ),
        .groupScheduleUpdate: APIContractRoute(
            id: .groupScheduleUpdate,
            method: .put,
            pathTemplate: "/groups/{groupId}/schedules/{scheduleId}",
            access: .authenticated
        ),
        .groupScheduleDelete: APIContractRoute(
            id: .groupScheduleDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/schedules/{scheduleId}",
            access: .authenticated
        ),
        .groupScheduleRun: APIContractRoute(
            id: .groupScheduleRun,
            method: .post,
            pathTemplate: "/groups/{groupId}/schedules/{scheduleId}/run",
            access: .authenticated
        ),
        .groupScheduleRuns: APIContractRoute(
            id: .groupScheduleRuns,
            method: .get,
            pathTemplate: "/groups/{groupId}/runs",
            access: .authenticated
        ),
        .groupRunCancel: APIContractRoute(
            id: .groupRunCancel,
            method: .post,
            pathTemplate: "/groups/{groupId}/runs/{runId}/cancel",
            access: .authenticated
        ),
        .groupTaskApproval: APIContractRoute(
            id: .groupTaskApproval,
            method: .post,
            pathTemplate: "/groups/{groupId}/runs/{runId}/tasks/{taskId}/approval",
            access: .authenticated
        ),
        .groupRoutinesList: APIContractRoute(
            id: .groupRoutinesList,
            method: .get,
            pathTemplate: "/groups/{groupId}/routines",
            access: .authenticated
        ),
        .groupRoutineRuns: APIContractRoute(
            id: .groupRoutineRuns,
            method: .get,
            pathTemplate: "/groups/{groupId}/routines/runs",
            access: .authenticated
        ),
        .groupRoutineCreate: APIContractRoute(
            id: .groupRoutineCreate,
            method: .post,
            pathTemplate: "/groups/{groupId}/routines",
            access: .authenticated
        ),
        .groupRoutineUpdate: APIContractRoute(
            id: .groupRoutineUpdate,
            method: .put,
            pathTemplate: "/groups/{groupId}/routines/{routineId}",
            access: .authenticated
        ),
        .groupRoutineDelete: APIContractRoute(
            id: .groupRoutineDelete,
            method: .delete,
            pathTemplate: "/groups/{groupId}/routines/{routineId}",
            access: .authenticated
        ),
        .groupRoutinePreview: APIContractRoute(
            id: .groupRoutinePreview,
            method: .post,
            pathTemplate: "/groups/{groupId}/routines/preview",
            access: .authenticated
        ),
        .pushTokenPut: APIContractRoute(
            id: .pushTokenPut,
            method: .put,
            pathTemplate: "/devices/push-token",
            access: .authenticated
        ),
        .pushTokenDelete: APIContractRoute(
            id: .pushTokenDelete,
            method: .delete,
            pathTemplate: "/devices/push-token",
            access: .authenticated
        ),
        .uploadCreate: APIContractRoute(
            id: .uploadCreate,
            method: .post,
            pathTemplate: "/uploads",
            access: .authenticated
        ),
        .uploadComplete: APIContractRoute(
            id: .uploadComplete,
            method: .post,
            pathTemplate: "/uploads/{fileId}/complete",
            access: .authenticated
        ),
        .fileDownload: APIContractRoute(
            id: .fileDownload,
            method: .get,
            pathTemplate: "/files/{fileId}/download",
            access: .authenticated
        ),
        .memoryList: APIContractRoute(
            id: .memoryList,
            method: .get,
            pathTemplate: "/memory",
            access: .authenticated
        ),
        .memoryCreate: APIContractRoute(
            id: .memoryCreate,
            method: .post,
            pathTemplate: "/memory",
            access: .authenticated
        ),
        .memoryExport: APIContractRoute(
            id: .memoryExport,
            method: .post,
            pathTemplate: "/memory/export",
            access: .authenticated
        ),
        .memoryUpdate: APIContractRoute(
            id: .memoryUpdate,
            method: .put,
            pathTemplate: "/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .memoryDelete: APIContractRoute(
            id: .memoryDelete,
            method: .delete,
            pathTemplate: "/memory/{memoryRecordId}",
            access: .authenticated
        ),
        .sharesList: APIContractRoute(
            id: .sharesList,
            method: .get,
            pathTemplate: "/shares",
            access: .authenticated
        ),
        .shareCreate: APIContractRoute(
            id: .shareCreate,
            method: .post,
            pathTemplate: "/shares",
            access: .authenticated
        ),
        .shareDelete: APIContractRoute(
            id: .shareDelete,
            method: .delete,
            pathTemplate: "/shares/{token}",
            access: .authenticated
        ),
        .shareImport: APIContractRoute(
            id: .shareImport,
            method: .post,
            pathTemplate: "/shares/{token}/import",
            access: .authenticated
        ),
        .skillCreate: APIContractRoute(
            id: .skillCreate,
            method: .post,
            pathTemplate: "/skills",
            access: .authenticated
        ),
        .githubSkillsScan: APIContractRoute(
            id: .githubSkillsScan,
            method: .post,
            pathTemplate: "/skills/github/scan",
            access: .authenticated
        ),
        .githubSkillPreview: APIContractRoute(
            id: .githubSkillPreview,
            method: .post,
            pathTemplate: "/skills/github/preview",
            access: .authenticated
        ),
        .skillGet: APIContractRoute(
            id: .skillGet,
            method: .get,
            pathTemplate: "/skills/{skillId}",
            access: .authenticated
        ),
        .skillUpdate: APIContractRoute(
            id: .skillUpdate,
            method: .put,
            pathTemplate: "/skills/{skillId}",
            access: .authenticated
        ),
        .skillShare: APIContractRoute(
            id: .skillShare,
            method: .post,
            pathTemplate: "/skills/{skillId}/share",
            access: .authenticated
        ),
        .skillShareImport: APIContractRoute(
            id: .skillShareImport,
            method: .post,
            pathTemplate: "/skill-shares/{token}/import",
            access: .authenticated
        ),
        .connectionsList: APIContractRoute(
            id: .connectionsList,
            method: .get,
            pathTemplate: "/connections",
            access: .authenticated
        ),
        .homeAssistantConnect: APIContractRoute(
            id: .homeAssistantConnect,
            method: .post,
            pathTemplate: "/connections/home-assistant",
            access: .authenticated
        ),
        .mcpServerConnect: APIContractRoute(
            id: .mcpServerConnect,
            method: .post,
            pathTemplate: "/connections/mcp-servers",
            access: .authenticated
        ),
        .mcpServerRename: APIContractRoute(
            id: .mcpServerRename,
            method: .patch,
            pathTemplate: "/connections/{connectionId}",
            access: .authenticated
        ),
        .connectionAuthorize: APIContractRoute(
            id: .connectionAuthorize,
            method: .post,
            pathTemplate: "/connections/{providerId}/authorization",
            access: .authenticated
        ),
        .connectionDelete: APIContractRoute(
            id: .connectionDelete,
            method: .delete,
            pathTemplate: "/connections/{connectionId}",
            access: .authenticated
        ),
        .accountDelete: APIContractRoute(
            id: .accountDelete,
            method: .delete,
            pathTemplate: "/account",
            access: .authenticated
        ),
    ]

    public static func route(_ id: APIRouteID) throws -> APIContractRoute {
        guard let route = routes[id] else { throw APIContractError.unknownRoute(id) }
        return route
    }
}
