import type { FrogBotApi } from './api';
import {
  demoBootstrap,
  demoBotDocuments,
  demoClearBotChat,
  demoDeleteBot,
  demoDeleteConnection,
  demoDeleteGroup,
  demoDeleteSchedule,
  demoGetSkill,
  demoGroupMessages,
  demoImportSkill,
  demoInstallBotTemplate,
  demoJoinGroup,
  demoListSchedules,
  demoMessages,
  demoRunSchedule,
  demoSaveBot,
  demoSaveConnection,
  demoSaveGroup,
  demoSaveSchedule,
  demoSaveSkill,
  demoSend,
  demoSendGroup,
} from './demo';

export const createDemoApi = (): FrogBotApi => ({
  invitePreview: async ({ kind, token }) => {
    const bootstrap = await demoBootstrap();
    return {
      kind,
      token,
      title: kind === 'group' ? 'Weekend builders' : 'A FroggyBot for you',
      description: 'Taylor invited you to bring people and FroggyBots together.',
      inviterName: 'Taylor',
      peopleCount: 3,
      bots: bootstrap.groups[0]?.bots ?? [],
      expiresAt: Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60,
    };
  },
  bootstrap: demoBootstrap,
  installBotTemplate: demoInstallBotTemplate,
  messages: async (botId) => demoMessages(botId),
  botDocuments: demoBotDocuments,
  saveBot: async (draft, botId) => demoSaveBot(draft, botId),
  clearBotChat: async (botId) => demoClearBotChat(botId),
  deleteBot: async (botId) => demoDeleteBot(botId),
  uploadAttachment: async (asset) => ({
    id: `demo-file-${Date.now()}`,
    name: asset.name,
    size: asset.size,
    kind: asset.mimeType?.startsWith('image/') ? 'image' : 'document',
    format: asset.name.split('.').pop()?.toLowerCase() ?? 'txt',
    contentType: asset.mimeType ?? 'application/octet-stream',
  }),
  downloadFile: async () => `data:text/plain;charset=utf-8,${encodeURIComponent('FroggyBot preview attachment')}`,
  sendMessage: async (bot, text) => demoSend(bot, text),
  cancelMessage: async () => {},
  approveMessage: async () => {},
  schedules: demoListSchedules,
  saveSchedule: demoSaveSchedule,
  deleteSchedule: demoDeleteSchedule,
  runSchedule: demoRunSchedule,
  groupMessages: async (groupId) => demoGroupMessages(groupId),
  saveGroup: async (draft, groupId) => demoSaveGroup(draft, groupId),
  deleteGroup: async (groupId) => demoDeleteGroup(groupId),
  sendGroupMessage: async (groupId, text, replyBotId) => demoSendGroup(groupId, text, replyBotId),
  shareGroup: async (groupId) => `https://froggybot.com/invite?kind=group&token=demo-${groupId}`,
  joinGroup: async (token) => demoJoinGroup(token),
  removeGroupMember: async () => {},
  registerPushToken: async () => {},
  unregisterPushToken: async () => {},
  sharedLinks: async () => [],
  memories: async () => ({ records: [], rawConversationRetentionDays: 30 }),
  updateMemory: async () => { throw new Error('Sign in to manage memory.'); },
  deleteMemory: async () => {},
  exportMemory: async () => { throw new Error('Sign in to export memory.'); },
  revokeShare: async () => {},
  deleteAccount: async () => {},
  share: async (botId, scope) => `https://froggybot.com/invite?kind=${scope}&token=demo-${scope}-${botId}`,
  importShare: async () => (await demoBootstrap()).bots[0],
  skill: demoGetSkill,
  saveSkill: demoSaveSkill,
  shareSkill: async (skillId) => `https://froggybot.com/invite?kind=skill&token=demo-${skillId}`,
  importSkill: demoImportSkill,
  saveConnection: demoSaveConnection,
  beginGmailConnection: async () => { throw new Error('Sign in to connect Gmail.'); },
  deleteConnection: async (connectionId) => demoDeleteConnection(connectionId),
});
