import type { Bot, Group, ScheduledTask } from './types';

export const createInitialDemoBots = (timestamp: string): Bot[] => [
  {
    id: 'trip-planner',
    name: 'Trip Planner',
    tagline: 'Turns everyone\'s preferences into a trip you can use.',
    color: '#3984F6',
    prompt: 'Plan practical group trips and finish with an itinerary, shared budget, packing list, and owner checklist.',
    toolIds: ['web', 'web_search', 'calculator', 'task_list', 'code_interpreter'],
    extraToolIds: [],
    skillIds: ['group-intake', 'trip-planner', 'shared-budget'],
    templateId: 'trip-planner',
    templateVersion: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    lastMessage: 'Tell me who is traveling and what matters most to each person.',
    lastMessageAt: timestamp,
  },
  {
    id: 'event-planner',
    name: 'Event Planner',
    tagline: 'Coordinates the decisions, costs, and checklist for an event.',
    color: '#F46A27',
    prompt: 'Coordinate group events with clear decisions, costs, owners, due dates, and a final run of show.',
    toolIds: ['web_search', 'calculator', 'task_list', 'code_interpreter'],
    extraToolIds: [],
    skillIds: ['group-intake', 'event-planner', 'group-decision', 'shared-budget'],
    templateId: 'event-planner',
    templateVersion: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    lastMessage: 'What are we organizing, and who needs to be involved?',
    lastMessageAt: timestamp,
  },
  {
    id: 'research-reports',
    name: 'Research & Reports',
    tagline: 'Finds reliable answers and turns them into useful files.',
    color: '#6C5CE7',
    prompt: 'Research broad questions with current sources, verify data with executable analysis, and create a useful report or editable file.',
    toolIds: ['web', 'web_search', 'task_list', 'delegate', 'calculator', 'code_interpreter'],
    extraToolIds: [],
    skillIds: ['deep-research', 'data-analyst'],
    templateId: 'research-reports',
    templateVersion: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    lastMessage: 'Give me the question or data, and I will return the useful conclusion.',
    lastMessageAt: timestamp,
  },
];

export const createInitialDemoGroups = (timestamp: string): Group[] => [{
  id: 'launch-room',
  name: 'Weekend in Portland',
  memory: 'Two adults leaving Boston Saturday morning. Keep the total under $1,200, avoid driving, include vegetarian food, and return by 6 PM Sunday.',
  ownerId: 'demo-user',
  currentUserId: 'demo-user',
  isOwner: true,
  members: [
    { id: 'demo-user', name: 'You', role: 'owner' },
    { id: 'jordan', name: 'Jordan', role: 'member' },
  ],
  bots: [],
  decisions: [],
  createdAt: timestamp,
  updatedAt: timestamp,
  lastMessage: 'Portland is the best fit. The itinerary and budget are ready.',
  lastMessageAt: timestamp,
}];

export const createInitialDemoSchedules = (timestamp: string): ScheduledTask[] => [{
  id: 'morning-priorities',
  botId: 'chief',
  name: 'Morning priorities',
  prompt: 'Review what we have discussed and give me the three most important priorities for today.',
  frequency: 'daily',
  time: '09:00',
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',
  enabled: true,
  createdAt: timestamp,
  updatedAt: timestamp,
}];
