export function Privacy() {
  return (<main className="doc-page" id="main">
    <p className="eyebrow">FroggyBot</p><h1>Privacy Policy</h1><p className="effective">Effective September 18, 2026</p>
    <p>This policy explains what FroggyBot collects, why we use it, and the choices available to you.</p>
    <h2>Information we collect</h2><p>We collect the email address used for passwordless authentication, bot configurations, conversation messages, and basic service records needed to operate and secure FroggyBot.</p><p>If you turn on a bot inbox, we collect email sent to that bot’s address, including the sender and recipient addresses, subject, message text, and attachment names. We briefly store the original email, including any attachments, while processing it. Messages in the bot inbox are available for you to review and delete; the bot does not act on them automatically.</p><p>If you choose phone-number sign-in, we collect the mobile number you provide and a record of your SMS consent. Providing a phone number and consenting to SMS are optional because email sign-in remains available.</p><p>If you allow reply notifications, we store a device push token. On supported Apple devices, dictation is requested as on-device speech recognition; FroggyBot does not intentionally upload or retain the audio recording.</p>
    <h2>How we use information</h2><p>We use this information to authenticate you, save bots and conversations, run requested agents, deliver notifications, prevent abuse, and maintain the service. Mobile numbers are used only to send user-requested one-time passcodes and related verification messages.</p><p>We do not sell personal information. Mobile numbers and SMS opt-in or consent data are not shared with third parties or affiliates for their own marketing or promotional purposes.</p>
    <h2>Service providers and sharing</h2><p>FroggyBot uses service providers, including Amazon Web Services and Expo, for authentication, agent processing, data storage, app updates, and notifications. They process information only as needed to provide those services.</p><p>A bot or conversation is shared only when you intentionally create a share link. Anyone with a valid link may be able to import the shared content, so treat share links as private.</p>
    <h2>SMS choices</h2><p>FroggyBot sends one transactional verification code only after you request one. Message frequency varies, and message and data rates may apply. Reply <strong>STOP</strong> to opt out or <strong>HELP</strong> for help. For US toll-free messages, text <strong>START</strong> or <strong>UNSTOP</strong> to the sending number to re-enable messages after opting out. See the <a href="/sms/">FroggyBot SMS program</a> and <a href="/terms/">Terms of Use</a> for details.</p>
    <h2>Retention and choices</h2><p>We retain account content and consent records while needed to provide FroggyBot, comply with legal obligations, resolve disputes, or protect the service. Bot inbox previews remain until you delete them or your account; original received email is stored temporarily for processing. You can turn off or replace a bot’s email address from its inbox. You can stop notifications in device settings and sign out at any time.</p><p>You can permanently delete your account and associated content from Account settings. Operational backups expire according to their limited retention schedule.</p>
    <h2>Security, children, and changes</h2><p>We use administrative and technical safeguards designed to protect information, but no online service can guarantee absolute security. FroggyBot is not directed to children under 13.</p><p>We may update this policy as the service changes. The effective date identifies the current version.</p>
  </main>);
}
