export function Terms() {
  return (<main className="doc-page" id="main">
    <p className="eyebrow">HeyTim</p><h1>Terms of Use</h1><p className="effective">Effective September 19, 2026</p><p>These terms set the basic rules for using HeyTim and its AI teammates.</p>
    <h2>Using HeyTim</h2><p>HeyTim provides AI assistants that can respond to messages and use the tools and skills you enable. You are responsible for your instructions, content, integrations, and lawful use of the service.</p><p>You must not use HeyTim to violate rights, distribute unlawful or harmful material, gain unauthorized access, or misrepresent automated output as verified professional advice.</p>
    <h2>Accounts and security</h2><p>You are responsible for access to the email account and devices used to sign in. Contact support through HeyTim’s App Store listing if you believe your account was accessed without permission.</p>
    <h2>SMS verification program</h2><p>HeyTim may offer optional passwordless sign-in by SMS. When you affirmatively opt in and request a code, HeyTim sends a transactional one-time passcode to the mobile number you provide. One message is sent per login attempt; message frequency varies. Message and data rates may apply. SMS consent is not a condition of purchase, and email sign-in remains available.</p><p>Reply <strong>STOP</strong> to opt out and <strong>HELP</strong> for help. For messages from a US toll-free number, carriers manage STOP requests at the network level. After opting out, text <strong>START</strong> or <strong>UNSTOP</strong> to the sending number to receive future verification codes. Mobile carriers are not liable for delayed or undelivered messages.</p><p>For SMS program information and customer care, visit <a href="/sms/">heytim.ai/sms</a>. Our handling of mobile numbers and consent records is described in the <a href="/privacy/">Privacy Policy</a>.</p>
    <h2>Your content and shared links</h2><p>You keep your rights in submitted content. You allow HeyTim and its service providers to process that content only as needed to operate, secure, and improve the service.</p><p>Creating a share link makes its included configuration or conversation available to anyone who receives it. Do not share confidential information unless you intend the recipient to receive it.</p>
    <h2>AI output</h2><p>AI systems can make mistakes or produce incomplete results. Review important output before relying on it, especially for legal, medical, financial, safety, or other high-impact decisions.</p>
    <h2>Plans, credits, and billing</h2><p>The Free plan currently includes 30 work credits per monthly period. HeyTim Plus currently includes 300 work credits for $20 per month. One work credit covers one bot reply or one planned group reply. Current prices and allowances are shown before checkout and may change for future billing periods with notice where required.</p><p>Plus renews automatically through Stripe until canceled. You can manage or cancel it from Usage &amp; Plan in HeyTim settings. Cancellation takes effect at the end of the current paid period unless otherwise stated; fees already charged are nonrefundable except where the law requires otherwise. If payment fails or a plan ends, the account returns to the Free allowance.</p>
    <h2>Availability and changes</h2><p>We may modify, suspend, or discontinue features and may restrict access needed to protect users or the service. HeyTim is provided on an as-available basis to the extent permitted by law.</p><p>We may update these terms as HeyTim evolves. Continued use after an updated effective date means you accept the revised terms.</p>
  </main>);
}
