[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FrogBot"
version = "0.1.0"
description = "AgentCore Runtime Application using Strands SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aws-opentelemetry-distro",
    "bedrock-agentcore >= 1.9.1",
    "botocore[crt] >= 1.35.0",
    "strands-agents >= 1.54.0, < 2.0.0",
    "strands-agents-stan @ git+https://github.com/strands-agents/stan.git@6ba1843a42ead5027e6896ffb21a7cc7cf95b9a8#subdirectory=stan-py",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true
