import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F8F7F3' },
  header: { minHeight: 58, paddingHorizontal: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#DDDAD2', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FBFBF9' },
  headerAction: { color: '#5D5A54', fontSize: 15 },
  primary: { color: '#007A3D', fontWeight: '700' },
  title: { maxWidth: '48%', fontSize: 16, fontWeight: '700', color: '#171714' },
  headerSpacer: { width: 62 },
  content: { padding: 20, paddingBottom: 60, maxWidth: 680, width: '100%', alignSelf: 'center' },
  tabs: { flexDirection: 'row', padding: 4, borderRadius: 14, backgroundColor: '#E9E7E1', marginTop: 18 },
  tab: { flex: 1, minHeight: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  tabActive: { backgroundColor: '#FFFFFF' },
  tabText: { color: '#77736B', fontSize: 13, fontWeight: '700' },
  tabTextActive: { color: '#007A3D' },
  sectionLabel: { color: '#24231F', fontSize: 13, fontWeight: '800', marginTop: 26, marginBottom: 10, textTransform: 'uppercase', letterSpacing: 0.7 },
  listHelp: { color: '#7B776F', fontSize: 13, lineHeight: 19, marginTop: -4, marginBottom: 12 },
  card: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 13, marginBottom: 9, borderRadius: 16, borderWidth: 1, borderColor: '#E2DFD7', backgroundColor: '#FFFFFF' },
  skillMark: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E4F1EA' },
  skillMarkText: { color: '#007A3D', fontSize: 17, fontWeight: '900' },
  cardText: { flex: 1, minWidth: 0 },
  nameRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  skillName: { flexShrink: 1, color: '#24231F', fontSize: 15, fontWeight: '700' },
  skillDescription: { color: '#7B776F', fontSize: 12, lineHeight: 17, marginTop: 4 },
  cardMeta: { color: '#918D84', fontSize: 10.5, lineHeight: 15, marginTop: 5 },
  badge: { alignSelf: 'flex-start', color: '#007A3D', backgroundColor: '#E4F1EA', overflow: 'hidden', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3, fontSize: 10, fontWeight: '700' },
  chevron: { color: '#9A968E', fontSize: 27, fontWeight: '300' },
  heroMark: { alignSelf: 'center', width: 68, height: 68, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#007A3D', marginTop: 14 },
  heroMarkText: { color: 'white', fontSize: 25, fontWeight: '900' },
  detailName: { color: '#1E1D19', fontSize: 25, fontWeight: '800', textAlign: 'center', marginTop: 15 },
  detailDescription: { color: '#716D66', fontSize: 15, lineHeight: 21, textAlign: 'center', marginTop: 7 },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, marginTop: 13 },
  version: { color: '#8B877F', fontSize: 11 },
  detailNote: { color: '#8B877F', fontSize: 12, lineHeight: 17, textAlign: 'center', marginTop: 9 },
  instructionsCard: { padding: 16, borderRadius: 15, borderWidth: 1, borderColor: '#D8D5CE', backgroundColor: '#FFFFFF' },
  instructions: { color: '#302F2A', fontSize: 14, lineHeight: 21 },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  toolPill: { color: '#075A31', backgroundColor: '#E4F1EA', overflow: 'hidden', borderRadius: 12, paddingHorizontal: 11, paddingVertical: 7, fontSize: 12, fontWeight: '700' },
  noTools: { color: '#858179', fontSize: 13, lineHeight: 19 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 32 },
  button: { flexGrow: 1, flexBasis: 190, minHeight: 47, borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  primaryButton: { backgroundColor: '#007A3D' },
  primaryButtonText: { color: 'white', fontSize: 14, fontWeight: '700' },
  secondaryButton: { borderWidth: 1, borderColor: '#D9D6CF', backgroundColor: 'white' },
  secondaryButtonText: { color: '#35332E', fontSize: 14, fontWeight: '700' },
  formIntro: { padding: 16, borderRadius: 17, backgroundColor: '#E9F4EE', marginBottom: 4 },
  formIntroTitle: { color: '#173E2A', fontSize: 15, fontWeight: '800' },
  formIntroText: { color: '#587363', fontSize: 13, lineHeight: 19, marginTop: 4 },
  fieldLabel: { color: '#24231F', fontSize: 14, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  fieldHelp: { color: '#858179', fontSize: 12, lineHeight: 17, marginTop: -4, marginBottom: 9 },
  input: { minHeight: 48, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: '#DDDAD2', backgroundColor: 'white', color: '#24231F', fontSize: 15 },
  instructionsInput: { minHeight: 260, lineHeight: 21 },
  characterCount: { color: '#9B978F', fontSize: 11, textAlign: 'right', marginTop: 5 },
  toolRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 13, marginBottom: 8, borderRadius: 14, borderWidth: 1, borderColor: '#E2DFD7', backgroundColor: 'white' },
  toolRowActive: { borderColor: '#8AB99F', backgroundColor: '#EAF5EF' },
  toolName: { color: '#2B2A25', fontSize: 14, fontWeight: '700' },
  check: { width: 22, height: 22, borderRadius: 7, borderWidth: 1, borderColor: '#C9C5BD', alignItems: 'center', justifyContent: 'center' },
  checkActive: { backgroundColor: '#007A3D', borderColor: '#007A3D' },
  checkText: { color: 'white', fontSize: 14, fontWeight: '800' },
  visibilityRow: { flexDirection: 'row', padding: 4, borderRadius: 14, backgroundColor: '#E9E7E1' },
  visibilityChoice: { flex: 1, minHeight: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  visibilityChoiceActive: { backgroundColor: 'white' },
  visibilityText: { color: '#77736B', fontSize: 13, fontWeight: '600' },
  visibilityTextActive: { color: '#007A3D' },
  loader: { marginTop: 80 },
  error: { color: '#A43C31', fontSize: 13, lineHeight: 18, marginTop: 16 },
  pressed: { opacity: 0.7 },
});
